### PR TITLE
Rename from directors to board (to match bylaws and handbook)

### PR DESCRIPTION
**Pull request by dcwalk**

### CODE REVIEW

**Review by patcon — APPROVED** [review]
Nice catch! No block, but I'm soft -0 on changing paths without figuring out layouts for redirects.

**Comment by patcon** [comment]
Like this: https://stackoverflow.com/a/19717455/504018

If looking for quick fix, would prefer we just change the human-readable title and deal with the dissonance of the url being wrong until time to do non-breaking change

**Comment by dcwalk** [comment]
I do not think we've linked to AGM notes from anywhere (yet-- I want to), are you saying we need to manage redirects before you would go ahead with this change? This seems so minor (1 file in 1 folder) that I am faar less worried about this than say what Iḿ about to do for templates

**Comment by patcon** [comment]
> are you saying we need to manage redirects

Fwiw "need to" is strong, and I'd never say we need to do anything unless i was blocking

But also, seeing that `path: directors-meetings/` is repo path, not browser url path, so original nit is moot! LGTM

**Comment by dcwalk** [comment]
There is a redirect gem we've used extensively with our networks we can add in (and I think maybe I could do that as part of the templates PR which feels far more breaking a rename) -> https://github.com/jekyll/jekyll-redirect-from

**Comment by dcwalk** [comment]
I'll  merge this, but pick up redirects in other PR :pray:

**Pull request merged**
