### PR TITLE
Auto-suggest converting issue numbers in notes to markdown links

### PR DESCRIPTION
**Pull request by patcon**
See this thread in fork for demo: https://github.com/patcon/organizing/pull/1

Basically, this uses an inline search-and-replace CLI tool to regex match on any mentions of `#123` or `priv#123` or `private#123` in the notes being added, and converts that notation into markdown links to our github issues.

e.g., `[private#123](https://github.com/hyphacoop/organizing-private/issues/123)`

Another GitHub Action tool then uses the diff to submit each fragment as a review comment with a "suggestion". These suggestions can be accepted in bulk and committer via the GitHub UI.

So to use this, we would send notes through the PR process even if we're doing self-merges now. the CI runs in 30 seconds, accepting all the comments is real quick in batch mode, and now our note notation will link straight to our issues for easy review :)

We could also use this strategy to do other processing of our notes, if we think of anything later

### Screenshot of PR review

Screen Shot 2021-02-14 at 4 17 55 AM

### CODE REVIEW

**Comment by patcon** [comment]
FYI

- `make` shows the help text
- `make link-issues` will run against all files in repo
- `make link-issues FILES="_posts/meeting-notes/fileA.md _posts/meeting-notes/fileB.md"` will run against specific files (this is what CI does, only on changed files in each PR)

I'll doc if this looks alright

**Comment by dcwalk** [comment]
Is this ready for discussion and review? And what is the flow?  review of PR first?

**Comment by patcon** [comment]
Yeah sorry, hard for me to stop pushing little changes, but it's done :)

Flow is just create a PR for notes as before, and it auto-suggests links within 30-60 seconds. (Won't work until merged, but will look like this: https://github.com/patcon/organizing/pull/1)

Docs are to explain how to do it locally, but not really expecting it to be used that way by anyone.

**Comment by dcwalk** [comment]
This looks great! Happy to merge it, if I understand you'll do another PR once merged somewhere if folks are interested in running it locally.

**Review by dcwalk — APPROVED** [review]

**Comment by patcon** [comment]
Thanks dc! I may be forgetting another comment I made elsewhere, but is this change (merged in this PR) enough for docs? https://github.com/hyphacoop/organizing/pull/397/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by patcon** [comment]
If I were to think of what's still missing, it might be a handbook page edit to mention how this runs (for cultivators to optionally do while archiving notes) :)

**Comment by dcwalk** [comment]
Oops, All looks good! No other docs expected!

**Pull request merged**
