### PR TITLE
Added ability to have per-section archive links in nav

### PR DESCRIPTION
**Pull request by patcon**
It can be a little confusing to add these otherwise

Screen Shot 2020-11-11 at 1 22 33 PM

### CODE REVIEW

**Comment by dcwalk** [comment]
I'm actually not seeing this behaviour @patcon -- I don't get the per-section archive links :thinking:

**Comment by patcon** [comment]
I'm easy on this. I was archiving a few private informational interviews at one point, and it seemed confusing to get them into the right subdirs in the two repos.

This adds similar links for subsections like this, like what we already have above for wg meetings. Does that make sense?

**Comment by patcon** [comment]
> as you want to go directly to the folder for archiving... right?

heh yeah, that was the primary intent (not the placement). But cutoffs and "see all" links seem like a good idea on their own too!

Also, more terse link text (emojis?) that link to the 3 places would also for suffice the purpose

> locally the includes aren't showing up.

I'll double-check in a bit :)

**Comment by patcon** [comment]
Seems to be working for me:

[](https://recordit.co/FlDg7nnwrS)

Was there something else you were expecting?

**Comment by dcwalk** [comment]
Re set this up and think I had some issue with a local branch not linked to origin.
Anyway, I'm fine with this incremental improvement, but this is an inconsistent UI element and I find the experience a little strange. Merging for now

**Review by dcwalk — APPROVED** [review]

**Pull request merged**
