### PR TITLE
Add Meditations On Moloch to reading pool and create general reading list

### PR DESCRIPTION
**Pull request by benhylau**
Until we find a better place to put these I am just going to keep piling them onto the reading pool :)

### CODE REVIEW

**Comment by dcwalk** [comment]
I'm still confused because I think the actual hackmd pad better serves this purpose than a static file. Why can't we just maintain that as a resource, but turn it into a more contemporary doc?

**Comment by benhylau** [comment]
If this is turning into a more general docs directory that has a general reading list, can we merge this? We don't currently have a live hackmd for tracking these.

**Comment by dcwalk** [comment]
Can we still use this hackpad? https://hackmd.io/_vUINRdvR1qlry3B5aNXqw
@patcon looks like he was on the same wavelength

**Comment by benhylau** [comment]
But how would someone discover https://hackmd.io/_vUINRdvR1qlry3B5aNXqw ? Why do we favour hackmd over having all resources in a github repo, and why are we against having resource additions as PRs?

Aren't we only using hackmd as temporary holding place? I use this pad as a list of articles I can reference.

I have pasted the content of the GitHub page to the hackmd to keep them in sync. If we like we can delete this page and replace it with a link to the hackmd.

**Comment by dcwalk** [comment]
> But how would someone discover https://hackmd.io/_vUINRdvR1qlry3B5aNXqw ? Why do we favour hackmd over having all resources in a github repo, and why are we against having resource additions as PRs?

We can add the link places

The tradeoff in my mind is whether a github md file is the best way to manage a (changing) resource list. My thought:
- Github PRs are less inviting/more onorous, esp. outside the org
- Github tends to be a place to keep static copies of docs, rather than living docs (my experience in multiple orgs
- Github flavoured markdown does not render as helpfully as a other alternatives (including hackmd)

It doesn't have to be a hackmd. If we think about this as a resource that we want to maintain we should talk about how.

I would also add that a reading pool probably makes more sense in our handbook than in this repo anyway

> 
> Aren't we only using hackmd as temporary holding place? I use this pad as a list of articles I can reference.
> 

We agreed to used Google Drive as a working/staging area (temporary), I don't think we had that discussion about hackmd. (Someone else correct me)

> I have pasted the content of the GitHub page to the hackmd to keep them in sync. If we like we can delete this page and replace it with a link to the hackmd.

**Comment by patcon** [comment]
- :heart: I feel agreement that GitHub might not be best place for living docs.

> > Aren't we only using hackmd as temporary holding place?
>
> We agreed to used Google Drive as a working/staging area (temporary), I don't think we had that discussion about hackmd. (Someone else correct me)

- :heart: I had the same impression that hackmd was a temp holding place.
  - :heart: I feel uncertain whether this was collectively discussed.
- :heart: I feel in agreement that hackmd isn't as discoverable, and doesn't feel first-class.
- :bulb: We could finish the [`backup2github`](https://github.com/hyphacoop/worker-coop-scripts#backup2github-command), the first scheduled task script I started, so it would pull from some [list of doc links](https://github.com/hyphacoop/worker-coop-scripts/blob/master/examples/files-to-backup.csv) and auto-open a per-doc PR when changes are made. (Related: https://github.com/hyphacoop/worker-coop-scripts/issues/1)

**Comment by patcon** [comment]
- :bulb: Rename this repo to something more general
  - :bulb: Create a subdir for `december-retreat` where we lock a snapshot of the reading list
  - :bulb: Copy a second, reading pool living doc that's ever expanding (with stuff like this PR) that we keep here until we decide how we want to treat living docs more permanently :)

**Comment by dcwalk** [comment]
@benhylau and @patcon -- I implemented the changes as laid out above, can you folks take a look and merge if good?

**Comment by benhylau** [comment]
Thanks @dcwalk this lgtm, I just cannot approve on GH bc the PR was made by me. @patcon pls merge if good for you.

**Pull request merged**
