### PR TITLE
Added copy of articles in version control

### PR DESCRIPTION
**Pull request by patcon**
Re-ticketed from https://github.com/hyphacoop/organizing/issues/103

### CODE REVIEW

**Comment by benhylau** [comment]
We have this in our drive, why duplicate this here?

**Comment by patcon** [comment]
because those are [a folder of dated sent/returned PDFs](https://drive.google.com/drive/u/0/folders/1FsqxrEhSTKW5h0Gtfrxl_wQLPoJgDbr4) that either (1) aren't viewable without download and using Adobe Acrobat, or (2) are scans and not OCR'd for easy copy-paste. Plus also, they have sensitive member info that must be redacted before anyone should ever share them outside our group.

This is public, shareable, and true version control, and if we wish, we can do PR flow for changes (which we already might need, given convos with Matt)

**Comment by benhylau** [comment]
We should either merge or close this. I personally don't understand why this needs to exist publicly, but if others feel the need please go ahead and merge. And cc. @YurkoWasHere if you have concerns.

**Comment by patcon** [comment]
Closing as not urgent.

**Pull request closed without merging**
